# Generated by Django 5.2.5 on 2026-02-24 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=20, unique=True)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('college', 'College Programs'), ('school', 'School Events'), ('corporate', 'Corporate Events'), ('private', 'Private Functions')], max_length=20)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=300)),
                ('performance_duration', models.FloatField(help_text='Hours')),
                ('expected_audience', models.IntegerField()),
                ('budget_min', models.IntegerField()),
                ('budget_max', models.IntegerField()),
                ('message', models.TextField()),
                ('preferred_contact', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10)),
                ('ai_category', models.CharField(choices=[('booking_request', 'Booking Request'), ('price_enquiry', 'Price Enquiry'), ('availability_enquiry', 'Availability Enquiry'), ('general_information', 'General Information'), ('complaint', 'Complaint')], default='general_information', max_length=30)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('manager_note', models.TextField(blank=True)),
                ('auto_reply_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='bands.bandprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.servicepackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
