# Generated by Django 5.2.5 on 2026-03-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_enquirymessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='budget_min',
        ),
    ]
