# Generated by Django 5.2.5 on 2026-03-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_remove_enquiry_budget_max_remove_enquiry_budget_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirymessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='message_attachments/'),
        ),
        migrations.AlterField(
            model_name='enquirymessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
