# Generated by Django 5.2.5 on 2026-02-24 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genres', models.JSONField(default=list)),
                ('event_types', models.JSONField(default=list)),
                ('base_location', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('location_tier', models.CharField(choices=[('metro', 'Metro City'), ('tier1', 'Tier-1 City'), ('tier2', 'Tier-2 City'), ('rural', 'Rural')], default='tier2', max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('instagram_url', models.URLField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='band_profiles/')),
                ('events_attended', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='band_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='band_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='bands.bandprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='bands.bandprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BandAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked'), ('booked', 'Booked'), ('pending', 'Pending')], default='available', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='bands.bandprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('band', 'date')},
            },
        ),
    ]
