# Generated by Django 5.2.5 on 2026-03-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Amount'), ('advance', 'Advance Amount'), ('offline', 'Offline (Pay Later)')], default='full', max_length=15),
        ),
    ]
